# Generated by Django 4.0.2 on 2022-03-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_created_on_todo_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_title',
        ),
    ]
